name: generate animation

on:
  # Executa automaticamente a cada 24 horas
  schedule:
    - cron: "0 */24 * * *"
  
  # Permite executar manualmente
  workflow_dispatch:
  
  # Executa em todo push na branch main
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: Joao-Pedro-de-0liveira-Ribeiro
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Move SVGs to root folder
        run: |
          mv dist/* ./

      - name: Commit and push SVGs to main
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add *.svg
          git commit -m "update contribution snake animation" || echo "No changes to commit"
          git push
